### ISSUE TITLE
Sentinel search form validation improvement nad handling 404 error for downloading non-existent data

### ISSUE THREAD

**Issue by danielkryska** [cyfronet-fid/sat4envi#1021]
- date input should have Validators.pattern(/[0-9]{4}-[0-9]{1,2}-[0-9]{1,2}/)
- number/float (cloudCover) inputs should have Validators.pattern(/([0-9]+,)?[0-9]+/)
- start date should be send to back-end with 00:00:00 time (convert example 2020-10-02 ->  2020-10-02T00:00:00)
- end date should be send to back-end with 23:59:59 time (convert example 2020-10-02 ->  2020-10-02T23:59:00)

**Comment by jswk** [comment]
> * date input should have Validators.pattern(/[0-9]{4}-[0-9]{1,2}-[0-9]{1,2}/)

I'd say rather: `[0-9]{4}-[0-9]{2}-[0-9]{2}`: the day and month must be zero-padded.

> * number/float (cloudCover) inputs should have Validators.pattern(/([0-9]+,)?[0-9]+/)

Here you should have a dot as a separator, so the regex becomes `[0-9]+\.?[0-9]*`. This handles most sensible cases, although excludes inputs such as `.5`, but requiring a user to input `0.5` instead seems fine to me.

> * end date should be send to back-end with 23:59:59 time (convert example 2020-10-02 ->  2020-10-02T23:59:00)

I'd follow with nines as far as possible, i.e. 2020-10-02 -> 2020-10-02T23:59:59.999999Z. You may miss some scenes otherwise.

**Comment by Marcelinna** [comment]
**handling 404 error for downloading non-existent data for products in Search data**

**Steps to reproduce**
1. Log as zkAdmin
2. Go to Search data
3. Choose MSG category
4. Choose Product (eg. Opad_H05_06h) and click the button <_Szukaj> (list of result is displayed)
5. click the download icon ![obraz](https://user-images.githubusercontent.com/59872096/106121547-f8412500-6157-11eb-9e9d-cc73726937f7.png), or open modal and click button <_Pobierz plik>

**What happens?**
backend returns 404 error, user sees an empty page

**What was expected to happen?**
error should be handling
