### ISSUE TITLE
Research OAuth2.0's Implicit Flow

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/sat4envi#171]
The main question which needs to be answered is how to handle access tokens over long period of time, and how to handle "remember me" feature in the login workflow.

**NOTE**: This issue has been created because `Password Grant` seems to not be widely used, and as such support for it is pretty low. That grant type is also pretty much depreciated by the community.

**Comment by jswk** [comment]
The decision is to implement implicit flow without refresh token for now.
Set the access token's validity to about a week.
Remove the persisting refresh token store for now, it probably won't be used anyway.
I opened a back-end ticket #178.

**Comment by jswk** [comment]
The previous decision has changed, and we abandon OAuth2 solution in favor of an in house one because of the insight from https://tools.ietf.org/html/draft-parecki-oauth-browser-based-apps-02#section-6.1.
Our app doesn't delegate authorization to a separate system, but relies on its own authorization and authentication methods. Also, there won't be any apps which would integrate with us as authorization server (AS).
For programmatic access we will probably roll-out some kind of API-key solution. My idea is to have an API gateway, which when provided with an API-key finds an associated JWT key and attaches it to the request, but it may be done differently, i.e. the idea is most likely flawed.
