### ISSUE TITLE
Fix people invitation thru sending Email

### ISSUE THREAD

**Issue by AndrzejWojcik** [cyfronet-fid/sat4envi#708]
When logged in as ZkAdmin, try to send an invitation thru Email. The invitation Email comes to the inbox, but when clicking on the "DOŁĄCZ" button, the user is logged in as the ZkAdmin.

1. Steps to reproduce:
a. Log in as Zkadmin
b. Go to settings.institutions
c. Choose an institution
d. Go to settings/people an click " WYŚLIJ ZAPROSZENIE" in the upper right corner
e. in the modal type a valid Email address, that inbox you can access and click "WYŚLIJ"
f. Close all web browser windows. in which You are logged in with ZkAdmin
g. Go to the inbox of this Email and click the button from the Email "DOŁĄCZ"
h. Try to register by clicking "Zarejestruj"

2. What should happen
The user, who gets invited should be able to register as a new user, who was invited.

3. What happened instead:
After clicking "Zarejestruj" the user is logged in as ZkAdmin.
Note: This is happening only when I open the link from the invitation mail in the normal mode on my browser (yes, I have the Zkadmin password and login saved in my chrome browser, but as written in 1.f., the session is closed). When I open the invitation link from the Email with Incognito mode, I am not able to register as a new user.

**Comment by danielkryska** [comment]
There are 3 ways (strictly 2) to be added to an institution

1. Log in as any user after going to the URL beneath button `DOŁĄCZ`
2. Register and then log in as a new user after going to the URL beneath button `DOŁĄCZ` (more or less same as 1, but with registration)
3. Being logged as a user and go to the URL beneath button `DOŁĄCZ`

This issue is a feature, not a bug. You just used the 3-rd option on the zkAdmin which invited himself. :P

Why did it happen?
Closing tabs don't remove the session of the web application where you were logged in. The best solution was to logout or run browser in private mode to have a clean session.
