### ISSUE TITLE
Problem with removing the institution

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/sat4envi#842]
Tested on instance https://sok.grid.cyfronet.pl
 SOK version v13.2.0

**Steps:**
1. Log in zkAdmin account 
2. Go to /settings/institution?institution=zarzadzenie-kryzysowe-pl
3. Select the child unit (e.g Zarządzanie kryzysowe - Podkarpacie) and click trash icon.
4. Confirm the deletion of the institution by clicking button <_OK>

**What happens?**
The user sees loading.... status in the place of child institutions that does not change
![obraz](https://user-images.githubusercontent.com/59872096/97284262-1fc6df80-1841-11eb-9479-5cce65a311de.png)

**What was expected to happen?**
The user sees list of child institution fo "Zarządzanie kryzysowe - PL"

5. Clik on the link "Lista instytucji"

**What happens?**
List of institutions isn't dispalyed
![obraz](https://user-images.githubusercontent.com/59872096/97285586-b0ea8600-1842-11eb-9675-254735ef3875.png)

**What was expected to happen?**
List of institutions is dispalyed

6. Click the link "Start"
7. Click the link "Lista instytucji"

**What happens?**
List of institutions ist dispalyed but deleted child isnt removed from the list. 
![obraz](https://user-images.githubusercontent.com/59872096/97286623-f8bddd00-1843-11eb-8034-85906b81c617.png)

**What was expected to happen?**
Selected before the child (Zarządzanie kryzysowe - Podkarpacie) is removed from the list.

**Comment by jswk** [comment]
For fixers from the future:
The problem is with not subscribing to pipe with a request in `institution.service.ts`:
![image](https://user-images.githubusercontent.com/583197/97696882-813bb800-1aa6-11eb-8175-08a6ccc75edb.png)
^^ get has a subscribe call, and delete doesn't.

In fact, in one place a subscribe is called in the caller metod:
![image](https://user-images.githubusercontent.com/583197/97696977-a5979480-1aa6-11eb-97ab-652dedac0ab0.png)
So, the handling has to be homogenized.
